apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('', views.index, name='index'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='user_logout'),
    path('relatorio-despesas/', views.relatorio, name='relatorio_despesas'),
    path('page-one/', views.page_one, name='page-one'),
]

emailbackend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
]

apps/accounts/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class Saldo(models.Model):

    saldo = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    meta = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    gastos = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    descricao = models.TextField(max_length=40, null=True, default="")
    created_at = models.DateTimeField(auto_now=True)
    total_gastos = models.DecimalField(max_digits=6, decimal_places=2, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'{self.gastos} {self.descricao}'


class Usuario(AbstractUser):
    email = models.EmailField(null=False, unique=True)

apps/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import Saldo

User = get_user_model()


class UserForm(forms.ModelForm):
    password = forms.CharField(label='Senha', widget=forms.TextInput(attrs={'type': 'password'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email já cadastrado!')
        return email

    class Meta:
        model = User
        fields = ['first_name', 'username', 'email', 'password']


# criação de form para saldo/gasto

class SaldoForm(forms.ModelForm):

    class Meta:
        model = Saldo
        fields = ['saldo', 'meta', 'gastos', 'descricao']

apps/accounts/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import F
from django.shortcuts import *
from .models import Saldo
from .forms import UserForm, SaldoForm


# Create your views here.


def cadastro(request):
    template_name = 'registro.html'
    context = {}
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            f = form.save()
            f.set_password(f.password)
            f.save()
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            login(request, user)
            Saldo.objects.create(saldo=0, meta=0, gastos=0, total_gastos=0, user=request.user).save()
            return redirect('accounts:page-one')
    else:
        form = UserForm()
    context['form'] = form
    return render(request, template_name, context)


def user_login(request):
    template_name = 'user_login.html'
    if request.method == 'POST':
        form = AuthenticationForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('accounts:page-one')
        else:
            messages.error(request, 'Usuario ou Senha incorreto!')
            return redirect('accounts:user_login')
    else:
        form = AuthenticationForm()
    return render(request, template_name, {'form': form})


def index(request):
    template_name = 'index.html'
    if request.user.is_authenticated:
        return redirect('accounts:page-one')
    return render(request, template_name)


@login_required(login_url='/login/')
def relatorio(request):
    if request.method == 'POST':
        month = request.POST.get('meses')
        year = request.POST.get('year')
        total = Saldo.objects.filter(user_id=request.user.id, created_at__month=month, created_at__year=year)
    else:
        data = datetime.now()
        mes = data.month
        ano = data.year
        total = Saldo.objects.filter(user_id=request.user.id, created_at__month=mes, created_at__year=ano)
    data = datetime.now()
    dia = data.strftime("%d")
    if str(dia) == '01':
        Saldo.objects.filter(user_id=request.user.id).update(saldo=0, meta=0, descricao='', gastos=0, total_gastos=0)

    res = Saldo.objects.get(user_id=request.user.id)
    context = {
        'total': total,
        'res': res,
        'dia': dia,
    }
    template_name = 'relatorio_despesas.html'
    return render(request, template_name, context)


@login_required(login_url='/login/')
def user_logout(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect('accounts:index')
    else:
        return redirect('accounts:user_login')


@login_required(login_url='/login/')
def page_one(request):
    saldo = get_object_or_404(Saldo, user_id=request.user.id)
    form = SaldoForm(instance=saldo)
    template_name = 'page-one.html'

    if request.method == 'POST':
        form = SaldoForm(request.POST, instance=saldo)
        if form.is_valid():
            saldo = form.save(commit=False)
            saldo.saldo = form.cleaned_data['saldo']
            saldo.meta = form.cleaned_data['meta']
            saldo.gastos = form.cleaned_data['gastos']
            saldo.descricao = form.cleaned_data['descricao']
            saldo.save()
            Saldo.objects.filter(user_id=request.user.id).update(saldo=F('saldo') - F('gastos'))
            Saldo.objects.filter(user_id=request.user.id).update(total_gastos=F('total_gastos') + F('gastos'))
            return redirect('accounts:page-one')
    return render(request, template_name, {'form': form})

templates/base.html
{% load static %}

<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%block link%}{%endblock%}
    <link rel="shortcut icon" href="{% static '/images/money-back.png' %}" type="image/x-png"/>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
    {% block link%}
        <link rel="stylesheet" href="{% static '/css/index.css' %}" type="text/css">
        <link rel="stylesheet" media="only screen and (max-width: 736px)" href="{% static '/css/index_mobile.css' %}" type="text/css"/>
    {% endblock%}

{% block title %}MyFinances{% endblock %}

{% block content %}
    <header id="cabecalho">
    <hgroup>
        <h1><img src="{% static '/images/money-back64.png' %}" width="45px"/> MyFinances</h1>
        <h2>Controle seus gastos de forma simples e rápida.</h2>
    </hgroup>
    <center>
        <img id="foto1" src="{% static '/images/controle-gastos.png' %}" align="right">
    </center>
    </header>
    <div id="menu">
        <ul>
            <li><a href="/cadastro">CRIAR CONTA</a></li>
            <li><a href="/login">ACESSE SUA CONTA</a></li>
        </ul>
    </div>
{% endblock %}

templates/page-one.html
{% extends 'base.html' %}

{% load static %}

    {% block link%}
        <link rel="stylesheet" type="text/css" href="{% static '/css/page_one.css' %}"/>
        <link rel="stylesheet" media="only screen and (max-width: 736px)" href="{% static '/css/page_one_mobile.css' %}" type="text/css"/>
    {% endblock %}

{% block title %}MyFinances{% endblock %}
{% block content %}
            <header id="cabecalho">
            <hgroup>
                <h1> <img src="{% static '/images/money-back64.png' %}"/> MyFinances</h1>
            </hgroup>
            </header>
            <div class="rel">
                <button><a href="{% url 'accounts:relatorio_despesas' %}">RELATÓRIO DE DESPESAS</a></button>
            </div>
            <form method="POST" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-default">SALVAR</button>
            </form>
            <div class="rodape">
                <img src="{% static '/images/page_one.png' %}">
            </div>
{% endblock %}

templates/principal.html
<style>
    input#saldo {
        margin-left: 80px;
        margin-top: -48px;
        width: 100px;
        height: 25px;
}
</style>

{% extends 'base.html' %}

{% block title %}Myfinances{% endblock %}

{% block content %}
    <h2><img src="static/images/money-back64.png"> MyFinances</h2>
    <form action="." method="post" autocomplete="off">
        {% csrf_token %}
        <input type="number" name="saldo" id="saldo" placeholder="saldo">
        <button type="submit">OK</button>
        <input type="number" name="meta" id="meta" placeholder="meta">
        <button type="submit">OK</button>
        <input type="number" name="gastos" id="gastos" placeholder="gastos">
        <button type="submit">OK</button>
    </form>
{% endblock %}
    <a href="{% url 'accounts:user_logout' %}">Fazer Logout</a>

templates/registro.html
{% extends 'base.html' %}

{% load static %}

    {% block link %}<link rel="stylesheet" href="{% static '/css/create.css' %}" type="text/css">
                    <link rel="stylesheet" media="only screen and (max-width: 736px)" href="{% static '/css/create_mobile.css' %}" type="text/css"/>
    {% endblock%}

{% block title %}MyFinances{% endblock %}

{% block content %}

    <h1><img src="{% static '/images/money-back64.png' %}" width="45px" style="margin-top: 10px;"/>MyFinances</h1>

    {% if messages %}
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    {% endif %}
<div class="login">
    <form method="post" autocomplete="off">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <h2>CADASTRE - SE</h2>
        <div class="errors">
            {{ form.email.errors }}
            {{ form.first_name.errors }}
            {{ form.username.errors }}
            {{ form.password.errors }}
        </div>
        <div id="first_name">
            <label for="{{ form.fist_name.id_for_label }}">Nome: </label>
            {{ form.first_name }}
        </div>
        <div id="username">
            <label for="{{ form.username.id_for_label }}">Usuario: </label>
            {{ form.username }}
        </div>
        <div id="email">
            <label for="{{ form.email.id_for_label }}">Email: </label>
            {{ form.email }}
        </div>
        <div id="Pass">
            <label for="{{ form.password.id_for_label }}">Senha: </label>
            {{ form.password }}
        </div>
        <button type="submit" id="log">Criar conta</button><br/>
        <a id="acesse" href="{% url 'accounts:user_login' %}">Fazer Login</a>
    </form>
</div>
{% endblock %}

templates/relatorio_despesas.html
{% extends 'base.html' %}
{% load static %}

    {% block link%}
            <link rel="stylesheet" href="{%static '/css/relatorio.css' %}">
            <link rel="stylesheet" media="only screen and (max-width: 736px)" href="{% static '/css/relatorio_mobile.css' %}" type="text/css"/>
    {% endblock %}

{% block title %}Myfinances{% endblock %}

{% block content %}
    <h2><a href="/page-one"><img src="{% static '/images/money-back64.png' %}" width="45px;" style="margin-left: 5px;
 margin-top: 5px;"></a> MyFinances</h2>
    {% csrf_token %}
<div class="login">
         <form role="form" method='post' action="{% url 'accounts:relatorio_despesas' %}">
             {% csrf_token %}
             <tr>
                 <td><select name="meses">

                    <option value="1">Janeiro</option>
                    <option value="2">Fevereiro</option>
                    <option value="3">Março</option>
                    <option value="4">Abril</option>
                    <option value="5">Maio</option>
                    <option value="6">Junho</option>
                    <option value="7">Julho</option>
                    <option value="8">Agosto</option>
                    <option value="9">Setembro</option>
                    <option selected value="10">Outubro</option>
                    <option value="11">Novembro</option>
                    <option value="12">Dezembro</option>
                     </select></td>

                  <td><select id="year" name="year">
                    <option selected value="2020">2020</option>
                    <option value="2021">2021</option>
                 </select></td>
            <td>
            <input type='submit' value='Procurar'/>
            </td>
             </tr>
            </form>
    {% for saldo in total %}
        <ul>
            <li class=gastos-item style="list-style: none;">
                <span><b>TOTAL GASTOS:</b> R${{saldo.total_gastos}}</span><br><br>
                <span><b>Data último gasto:</b> {{saldo.created_at}}</span><br><br>
                <span><b>Descrição último gasto:</b> {{saldo.descricao}}</span><br><br>
            </li>
        </ul>
    {% endfor %}
    {% if res.total_gastos > res.meta and dia == '28' %}
        <p id="fail">Você ultrapassou a meta este mês!</p>
    {% endif %}
    {% if res.total_gastos == res.meta and dia == '28' %}
        <p id="ok">Você atingiu exatamente a meta esperada!</p>
    {% endif %}
    {% if res.total_gastos < res.meta and dia == '28' %}
        <p id="sucess">Você ficou abaixo da meta, Parabéns!!</p>
    {% endif %}
    <img src="{% static '/images/relatorio.png' %}" width="70%"/>
    <a href="{% url 'accounts:user_logout' %}" style="text-decoration: none;">FAZER LOGOUT</a>
</div>
{% endblock %}

templates/user_login.html
{% extends 'base.html' %}
{% load static %}


    {% block link%}
        <link rel="stylesheet" href="{% static '/css/login.css' %}" type="text/css">
        <link rel="stylesheet" media="only screen and (max-width: 736px)" href="{% static '/css/login_mobile.css' %}" type="text/css"/>
    {% endblock%}

{% block title%}MyFinances{% endblock%}

{% block content %}
    <div class="title">
        <h1><img src="{% static '/images/money-back64.png' %}" width="45px" style="margin-top: 10px;"/>MyFinances</h1>
    </div>
        <div class="login">
            <form method="post" autocomplete="off">
                {% csrf_token %}
                <h2>LOGIN</h2>
                {% for message in messages %}
                    <div class="alert">
                        {{ message }}
                    </div>
                {% endfor %}
                <label id="usuario">Usuario:</label>
                <input type="text" name="username" id="username" maxlength="100" placeholder="Usuário ou Email">
                <label id="senha">Senha:<input type="password" name="password" id="password" maxlength="12" placeholder="Senha"></label>
                <button type="submit" id="log">Entrar</button>
                <a href="{% url 'accounts:cadastro' %}">Cadastre-se agora!</a>
            </form>
        </div>
{% endblock %}